" Pieced together from various sources, including:
" * https://github.com/carlhuda/janus/blob/master/gvimrc

"set lines=40
"set columns=130

" Start without the toolbar
set guioptions-=T

"colorscheme motus

" We need these commands to run after syntax highlighting
"highlight NonText guifg=#666666
"highlight SpecialKey guifg=#666666

if has("gui_macvim")
    " Fullscreen takes up entire screen
    set fuoptions=maxhorz,maxvert

    if exists("g:peepopen_loaded")
        macmenu &File.New\ Tab key=<nop>
        map <D-t> <Plug>PeepOpen
    endif

    " Command-Return for fullscreen
    macmenu Window.Toggle\ Full\ Screen\ Mode key=<D-CR>
endif

" auto source .gvimrc changes
autocmd bufwritepost .gvimrc source $MYGVIMRC
autocmd bufwritepost gvimrc source $MYGVIMRC

nmap <leader>h :call HexHighlight()<Return>
