export ZSH=$HOME/.oh-my-zsh

# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="mrtazz"

plugins=(brew gem git osx ruby svn ssh-agent vi-mode)

source $ZSH/oh-my-zsh.sh

alias ll="ls -Al"

# Applications completion
if test "$(uname)" = "Darwin"; then
   compctl -f -x 'p[2]' -s "`/bin/ls -d1 /Applications/*/*.app /Applications/*.app | sed 's|^.*/\([^/]*\)\.app.*|\\1|;s/ /\\\\ /g'`" -- open
   alias run='open -a'
fi

