#! /bin/sh

function mkvimdir() { [ -d ~/.vim/$1 ] || mkdir ~/.vim/$1; }

function gitinstall() {
    repo=`basename $1 .git`
    if [ -d ~/.vim/repos/$repo ]; then
        echo "Updating $repo..."
        pushd ~/.vim/repos/$repo > /dev/null 2>&1
        git pull
    else
        echo "Installing $repo..."
        pushd ~/.vim/repos > /dev/null 2>&1
        git clone $1 > /dev/null 2>&1
        cd $repo
    fi

    for dir in `ls`; do
        if [ -d $dir ]; then
            mkvimdir $dir
            cp -rf $dir/* ~/.vim/$dir/
        fi
    done
    popd > /dev/null 2>&1
}

# Make sure directories exist
mkvimdir backup
mkvimdir repos

# Install base plugins
gitinstall git://github.com/tpope/vim-surround.git
gitinstall git://github.com/wycats/nerdtree.git
gitinstall git://github.com/vim-scripts/taglist.vim.git
gitinstall git://github.com/scrooloose/syntastic.git
gitinstall git://github.com/mileszs/ack.vim.git
gitinstall git://github.com/tpope/vim-fugitive.git
gitinstall git://github.com/tpope/vim-git.git
gitinstall git://github.com/michaeljsmith/vim-indent-object.git
gitinstall git://github.com/pangloss/vim-javascript.git
gitinstall git://github.com/hallettj/jslint.vim.git
gitinstall git://github.com/robgleeson/vim-markdown-preview.git
gitinstall git://github.com/ddollar/nerdcommenter.git
gitinstall git://github.com/ervandew/supertab.git
gitinstall git://github.com/tpope/vim-cucumber.git
gitinstall git://github.com/timcharper/textile.vim.git
gitinstall git://github.com/tpope/vim-rails.git
gitinstall git://github.com/taq/vim-rspec.git
gitinstall git://github.com/vim-scripts/ZoomWin.git
gitinstall git://github.com/msanders/snipmate.vim.git
gitinstall git://github.com/tpope/vim-markdown.git
gitinstall git://github.com/tsaleh/vim-align.git
gitinstall git://github.com/tpope/vim-unimpaired.git
gitinstall git://github.com/tpope/vim-endwise.git
gitinstall git://github.com/kchmck/vim-coffee-script.git
gitinstall git://github.com/ajf/puppet-vim.git
gitinstall git://github.com/bdd/vim-scala.git

# Add command-t https://wincent.com/products/command-t

vim -e -s <<-EOF\n:helptags ~/.vim/doc\n:quit\nEOF

