#!/bin/bash
#
# Initialize POSIX configuration, symlinking configuration files
# to this directory, and shell scripts to ~/scripts.
# This script is idempotent, and ensures that existing dotfiles, as well
# as the contents of the ~/scripts directory, will be removed.
# This is intentional - it forces me to maintain everything here rather
# than separately on each machine I work on.

#set -e

function remove() {
echo "Removing $1"
    test -e $1 && rm -rf $1
}

remove ~/git-completion.bash
remove ~/.oh-my-zsh
remove ~/.nvm

# Change to zsh and use oh-my-zsh
chsh -s /bin/zsh
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

wget -O ~/git-completion.bash --no-check-certificate https://github.com/git/git/raw/next/contrib/completion/git-completion.bash

# Used in bash profile
git clone git://github.com/creationix/nvm.git ~/.nvm
bash -s stable < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)

